Repository pyproj4/pyproj, pull requests merged in 2022-12, with the labels that each got.

#1201 ENH: Add inplace kwarg to Geod.fwd and Geod.inv
  pyproj/geod.py
  test/test_geod.py
Labels: enhancement

#1205 PERF: Faster transform direction if already passed an Enum
  pyproj/_transformer.pyx
Labels: enhancement

#1210 TST: Fix expected tranform grid list for bbox
  test/test_sync.py
Labels: proj, test

#1211 TST: move tests using NADCON grids to test_transform
  pyproj/transformer.py
  test/conftest.py
  test/test_transform.py
Labels: proj, test

#1204 PERF: Optimize point transformations
  .pylintrc
  docs/history.rst
  pyproj/_transformer.pyi
  pyproj/_transformer.pyx
  pyproj/proj.pxi
  pyproj/transformer.py
  test/conftest.py
  test/test_transformer.py
Labels: enhancement

#1206 PERF: Optimize for single point in Geod fwd/inv functions
  pyproj/_geod.pyi
  pyproj/_geod.pyx
  pyproj/geod.py
  test/test_geod.py
Labels: enhancement

#1215 TST:geod: Separate geodesic tests for clarity
  test/test_geod.py
Labels: test

#1216 TST:geod: Use scalar_and_array in fwd/inv tests
  test/conftest.py
  test/test_geod.py
Labels: test

#1222 BUG: Fix Derived Projected CRS support
  docs/history.rst
  pyproj/_crs.pyx
  pyproj/database.pyx
  pyproj/enums.py
  pyproj/proj.pxi
  test/crs/test_crs.py
  test/crs/test_crs_maker.py
  test/test_database.py
Labels: bug, enhancement
