Repository pyproj4/pyproj, pull requests merged in 2024-02, with the labels that each got.

#1378 LNT: Update pre-commit pins and reformat
  .pre-commit-config.yaml
  pyproj/__init__.py
  pyproj/_show_versions.py
  pyproj/aoi.py
  pyproj/crs/_cf1x8.py
  pyproj/crs/coordinate_operation.py
  pyproj/crs/coordinate_system.py
  pyproj/crs/crs.py
  pyproj/crs/datum.py
  pyproj/crs/enums.py
  pyproj/datadir.py
  pyproj/enums.py
  pyproj/exceptions.py
  pyproj/network.py
  pyproj/proj.py
  pyproj/sync.py
  pyproj/transformer.py
  pyproj/utils.py
  test/crs/test_crs.py
  test/test_datadir.py
  test/test_doctest_wrapper.py
  test/test_pickle.py
  test/test_transformer.py
Labels: dependencies

#1380 BUG: Support azimuthal_equidistant coordinate operation to CF
  pyproj/crs/_cf1x8.py
Labels: bug

#1379 CI: Enable macos arm runner
  .cirrus.yml
  .github/workflows/release.yaml
Labels: test, macos

#1383 Add is_deprecated and get_non_deprecated() to CRS
  docs/history.rst
  pyproj/_crs.pyi
  pyproj/_crs.pyx
  pyproj/crs/crs.py
  pyproj/proj.pxi
  test/crs/test_crs.py
Labels: enhancement
